kind: Deployment
apiVersion: apps/v1
metadata:
  name: bull-server
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/bull-server
  uid: a98d11da-ee4a-4e41-9b6b-2a47ca8a7480
  resourceVersion: "78952"
  generation: 16
  creationTimestamp: "2020-01-13T20:08:06Z"
  labels:
    app: bull-server
  annotations:
    deployment.kubernetes.io/revision: "12"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bull-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bull-server
    spec:
      containers:
        - name: bull-server
          image: "grantmcdonald/bull-server:11"
          envFrom:
            - configMapRef:
                name: config
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 16
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: "True"
      lastUpdateTime: "2020-01-14T23:32:25Z"
      lastTransitionTime: "2020-01-14T23:32:25Z"
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: "True"
      lastUpdateTime: "2020-01-15T20:54:52Z"
      lastTransitionTime: "2020-01-13T20:08:06Z"
      reason: NewReplicaSetAvailable
      message: ReplicaSet "bull-server-7856d6f9d6" has successfully progressed.
