apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bull-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bull-server
    spec:
      containers:
        - name: bull-server
          image: hub.docker.com/repository/docker/grantmcdonald/bull-server
          ports:
            - containerPort: 80
