apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "8"
    creationTimestamp: "2020-01-13T20:08:06Z"
    generation: 12
    labels:
      app: bull-server
    name: bull-server
    namespace: default
    resourceVersion: "29829"
    selfLink: /apis/apps/v1/namespaces/default/deployments/bull-server
    uid: a98d11da-ee4a-4e41-9b6b-2a47ca8a7480
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: bull-server
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: bull-server
      spec:
        containers:
        - image: grantmcdonald/bull-server:9
          imagePullPolicy: IfNotPresent
          name: bull-server
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2020-01-14T21:34:36Z"
      lastUpdateTime: "2020-01-14T21:34:36Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-01-13T20:08:06Z"
      lastUpdateTime: "2020-01-14T21:37:32Z"
      message: ReplicaSet "bull-server-75b56bb958" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 12
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
