apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "10"
    creationTimestamp: "2020-01-13T20:12:34Z"
    generation: 41
    labels:
      app: bull-worker
    name: bull-worker
    namespace: default
    resourceVersion: "33349"
    selfLink: /apis/apps/v1/namespaces/default/deployments/bull-worker
    uid: 966137c6-bbcd-46ec-b1a5-fc617dba94df
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: bull-worker
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: bull-worker
      spec:
        containers:
        - image: grantmcdonald/bull-worker:10
          imagePullPolicy: IfNotPresent
          name: bull-worker
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2020-01-13T20:12:34Z"
      lastUpdateTime: "2020-01-14T21:55:54Z"
      message: ReplicaSet "bull-worker-7867d7584c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2020-01-14T21:57:40Z"
      lastUpdateTime: "2020-01-14T21:57:40Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 41
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
