kind: Deployment
apiVersion: apps/v1
metadata:
  name: bull-worker
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/bull-worker
  uid: 966137c6-bbcd-46ec-b1a5-fc617dba94df
  resourceVersion: "79171"
  generation: 47
  creationTimestamp: "2020-01-13T20:12:34Z"
  labels:
    app: bull-worker
  annotations:
    deployment.kubernetes.io/revision: "14"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bull-worker
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bull-worker
    spec:
      containers:
        - name: bull-worker
          image: "grantmcdonald/bull-worker:12"
          envFrom:
            - configMapRef:
                name: config
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 47
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: "True"
      lastUpdateTime: "2020-01-15T20:53:46Z"
      lastTransitionTime: "2020-01-13T20:12:34Z"
      reason: NewReplicaSetAvailable
      message: ReplicaSet "bull-worker-645d865dd6" has successfully progressed.
    - type: Available
      status: "True"
      lastUpdateTime: "2020-01-15T20:55:41Z"
      lastTransitionTime: "2020-01-15T20:55:41Z"
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
