version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/worker"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/server"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/server"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/worker"
    update_schedule: "daily"
